CREATE TABLE question (
    id INT AUTO_INCREMENT PRIMARY KEY,
    texte VARCHAR(255) NOT NULL,
    idquiz INT NOT NULL,
    CONSTRAINT FK_QUIZ_QUESTION FOREIGN KEY (idquiz) REFERENCES quiz(idquiz) ON DELETE CASCADE
);

CREATE TABLE answer (
    id INT AUTO_INCREMENT PRIMARY KEY,
    texte VARCHAR(255) NOT NULL,
    correct TINYINT(1) NOT NULL DEFAULT 0,
    question_id INT NOT NULL,
    CONSTRAINT FK_ANSWER_QUESTION FOREIGN KEY (question_id) REFERENCES question(id) ON DELETE CASCADE
);
